#!/sbin/openrc-run
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

pidfile="/run/${RC_SVCNAME}.pid"
command="/usr/bin/cgrulesengd"
command_args="${CGRED_OPTS}"
command_background=true
description="CGroups Rules Engine Daemon"
extra_started_commands="reload"

depend()
{
	need cgconfig
	use logger
}

reload()
{
	ebegin "Reloading CGroup Rules Engine Daemon"
	kill -USR2 $(cat "${pidfile}")
	eend $?
}
